#!/usr/bin/env bash
# CyberHygiene Project Lab Installer — based on Rocky Linux 9.
# Not an official Rocky Linux product.
# Rocky Linux is a trademark of the Rocky Enterprise Software Foundation.
# build-iso.sh REPO_V ISO_V (RUNS ON AERO, sudo): the Rocky 9.8 DVD + signed repo REPO_V + /data/chp-release/iso-src
# -> /var/lib/libvirt/images/chp-iso/ISO_V/cyberhygiene-lab-installer-el9.iso. The boot files (shim, grub, kernel,
# initrd) are the DVD's, unchanged; the boot records are rebuilt with the DVD's own options; menus and /chp are new.
set -Eeuo pipefail
[[ $EUID -eq 0 ]] || { echo "run with sudo"; exit 1; }
REPO_V=$1 ISO_V=$2
DVD=/data/lab-inputs/Rocky-9.8-x86_64-dvd.iso
DVD_SHA=d2bcbb64c2d67511adf80d40cd9543391a33aea5860a355b1d26d7f55236d01f
REPO=/data/chp-release/$REPO_V/repo TOOLS=/data/chp-release/tools SRC=/data/chp-release/iso-src
OUT=/var/lib/libvirt/images/chp-iso/$ISO_V NAME=cyberhygiene-lab-installer-el9.iso VOLID=CHP-LAB-EL9
[[ -e $OUT ]] && { echo "refusing: $OUT exists"; exit 1; }
for f in grub.cfg isolinux.cfg server.ks client.ks chp-site.pyz NOTICE.txt; do
  [[ -f $SRC/$f ]] || { echo "refusing: $SRC/$f missing (run appliance/iso/push.sh on the Mac)"; exit 1; }
done
avail=$(df --output=avail -B1G /var/lib/libvirt/images | tail -1 | tr -d ' ')
(( avail >= 20 )) || { echo "refusing: only ${avail} GB free under /var/lib/libvirt/images (need 20)"; exit 1; }
echo "== DVD: sha256 (takes about a minute)"
[[ $(sha256sum "$DVD" | cut -d' ' -f1) == "$DVD_SHA" ]] || { echo "refusing: DVD sha256 differs from the pin"; exit 1; }
echo "== repo $REPO_V: signatures"
bash "$TOOLS/verify-repo.sh" "$REPO" "$TOOLS"
(( $(df --output=avail -B1G /backup | tail -1 | tr -d ' ') >= 20 )) || { echo "refusing: need 20 GB free on /backup (work tree)"; exit 1; }
W=$(mktemp -d -p /backup chp-iso.XXXXXX); m=$W/mnt dvd=$W/dvd T=$W/tree; mkdir "$m" "$dvd" "$T"
trap 'for d in "$m" "$dvd"; do mountpoint -q "$d" && umount "$d"; done; rm -rf "$W"' EXIT
echo "== DVD tree -> work copy (about 15 GB, on /backup)"
mount -o loop,ro "$DVD" "$dvd"; cp -a "$dvd"/. "$T"/; umount "$dvd"; chmod -R u+w "$T"
rm -f "$T/isolinux/boot.cat"                       # regenerated by -c below
echo "== stage /chp, menus, NOTICE"
mkdir -p "$T/chp/ks"
cp -a "$REPO"/. "$T/chp/"
install -m 0644 "$SRC/chp-site.pyz" "$T/chp/chp-site.pyz"
install -m 0644 "$SRC/server.ks" "$SRC/client.ks" "$T/chp/ks/"
install -m 0644 "$SRC/grub.cfg" "$T/EFI/BOOT/grub.cfg"          # /EFI/BOOT/grub.cfg
install -m 0644 "$SRC/isolinux.cfg" "$T/isolinux/isolinux.cfg"  # /isolinux/isolinux.cfg
install -m 0644 "$SRC/NOTICE.txt" "$T/NOTICE.txt"               # /NOTICE.txt
echo "== /images/efiboot.img: our grub.cfg (DVD and USB UEFI boot read this copy; the EFI binaries are not touched)"
mount -o loop "$T/images/efiboot.img" "$m"
[[ -f $m/EFI/BOOT/grub.cfg ]] || { echo "efiboot.img has no EFI/BOOT/grub.cfg"; exit 1; }
cp "$SRC/grub.cfg" "$m/EFI/BOOT/grub.cfg"; sync; umount "$m"
# The DVD's own boot options (xorriso -report_el_torito as_mkisofs of the DVD). Not "-boot_image any replay": that
# re-used the DVD's ORIGINAL EFI image as an appended partition (Rocky menu; found on ISO 0.1.0-rc1 by check-iso.sh).
echo "== ISO"
mkdir -p "$OUT"
xorriso -as mkisofs -o "$OUT/$NAME" -V "$VOLID" -R -J -joliet-long -iso-level 3 \
  -isohybrid-mbr --interval:local_fs:0s-15s:zero_mbrpt,zero_gpt:"$DVD" \
  -partition_cyl_align off -partition_offset 0 --mbr-force-bootable -iso_mbr_part_type 0x00 \
  -c isolinux/boot.cat -b isolinux/isolinux.bin -no-emul-boot -boot-load-size 4 -boot-info-table \
  -eltorito-alt-boot -e images/efiboot.img -no-emul-boot -isohybrid-gpt-basdat \
  "$T" 2>&1 | tail -3
(cd "$OUT" && sha256sum "$NAME" > SHA256SUMS)
{ echo "ISO $ISO_V built $(date -u +%Y-%m-%dT%H:%M:%SZ) on $(hostname -s)"
  echo "DVD Rocky-9.8-x86_64-dvd.iso sha256 $DVD_SHA"
  echo "repo $REPO_V repomd.xml sha256 $(sha256sum "$REPO/repodata/repomd.xml" | cut -d' ' -f1)"
  for f in chp-site.pyz server.ks client.ks grub.cfg isolinux.cfg NOTICE.txt; do echo "$f sha256 $(sha256sum "$SRC/$f" | cut -d' ' -f1)"; done
  echo "xorriso $(xorriso -version 2>/dev/null | head -1)"
  cat "$OUT/SHA256SUMS"; } > "$OUT/BUILD-RECORD.txt"
chmod 0644 "$OUT"/*
echo "built: $OUT/$NAME"
