version = "2"
bindaddress = "192.168.100.10:443"
db_path = "/var/lib/private/kanidm/kanidm.db"
tls_chain = "/run/credentials/kanidmd.service/tls_chain"
tls_key = "/run/credentials/kanidmd.service/tls_key"
domain = "idm.kanidm.lab.test"
origin = "https://idm.kanidm.lab.test"
log_level = "info"

[online_backup]
path = "/var/lib/private/kanidm/backups/"
schedule = "00 22 * * *"
versions = 7
